'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _Default

    '''<summary>
    '''grdAccumulations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdAccumulations As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''depurar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents depurar As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''OnTimeApproval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OnTimeApproval As Global.System.Web.UI.DataVisualization.Charting.Chart

    '''<summary>
    '''OnTimeApprovalDays control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OnTimeApprovalDays As Global.System.Web.UI.DataVisualization.Charting.Chart

    '''<summary>
    '''txtfecha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtfecha As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlPeriod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPeriod As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''imgbtnsubmitapproval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgbtnsubmitapproval As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lblbaddate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblbaddate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OntimeSent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OntimeSent As Global.System.Web.UI.DataVisualization.Charting.Chart

    '''<summary>
    '''Updatepanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Updatepanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''SentOnTimeAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SentOnTimeAll As Global.System.Web.UI.DataVisualization.Charting.Chart

    '''<summary>
    '''txtOntimeSentDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOntimeSentDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlontimesent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlontimesent As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''imgbtnrefreshontimesent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgbtnrefreshontimesent As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lblinvalidDate2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblinvalidDate2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chartDD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chartDD As Global.System.Web.UI.DataVisualization.Charting.Chart

    '''<summary>
    '''chartChecksprocs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chartChecksprocs As Global.System.Web.UI.DataVisualization.Charting.Chart

    '''<summary>
    '''dailyLoginCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dailyLoginCount As Global.System.Web.UI.DataVisualization.Charting.Chart

    '''<summary>
    '''Updatepanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Updatepanel2 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''loginbyplatformall control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loginbyplatformall As Global.System.Web.UI.DataVisualization.Charting.Chart

    '''<summary>
    '''txtLoginDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLoginDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlranges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlranges As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''imgbtngetlogins control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgbtngetlogins As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lblloginbaddate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblloginbaddate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chartReconcil control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chartReconcil As Global.System.Web.UI.DataVisualization.Charting.Chart

    '''<summary>
    '''Updatepanel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Updatepanel3 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''reconcilall control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reconcilall As Global.System.Web.UI.DataVisualization.Charting.Chart

    '''<summary>
    '''txtallreconcil control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtallreconcil As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlallreconcil control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlallreconcil As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''imgbtnallreconcil control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgbtnallreconcil As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lblallreconcil control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblallreconcil As Global.System.Web.UI.WebControls.Label
End Class
